/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package miniproyectopoo;

import java.awt.BorderLayout;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luisc
 */
public class PanelMenu extends javax.swing.JPanel {

    private VentanaPrincipal ventanaPrincipal;
    private AgregarContacto agregarContacto;
    private DefaultTableModel modelo;
    private EditarContacto editarContacto;
    /**
     * Creates new form PanelMenu
     */
    public PanelMenu(VentanaPrincipal ventanaPrincipal) {
        this.ventanaPrincipal = ventanaPrincipal;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaTitulo1 = new javax.swing.JLabel();
        etiquetaMenu2 = new javax.swing.JLabel();
        botonAgregarContacto = new javax.swing.JButton();
        botonEditarContacto = new javax.swing.JButton();
        botonBuscarContacto = new javax.swing.JButton();
        botonEliminarContacto = new javax.swing.JButton();

        etiquetaTitulo1.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        etiquetaTitulo1.setText("GESTOR DE CONTACTOS");

        etiquetaMenu2.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        etiquetaMenu2.setText("MENU PRINCIPAL");

        botonAgregarContacto.setText("AGREGAR");
        botonAgregarContacto.setFocusable(false);
        botonAgregarContacto.setPreferredSize(new java.awt.Dimension(100, 30));
        botonAgregarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarContactoActionPerformed(evt);
            }
        });

        botonEditarContacto.setText("EDITAR");
        botonEditarContacto.setFocusable(false);
        botonEditarContacto.setPreferredSize(new java.awt.Dimension(100, 30));
        botonEditarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarContactoActionPerformed(evt);
            }
        });

        botonBuscarContacto.setText("BUSCAR");
        botonBuscarContacto.setFocusable(false);
        botonBuscarContacto.setPreferredSize(new java.awt.Dimension(100, 30));
        botonBuscarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarContactoActionPerformed(evt);
            }
        });

        botonEliminarContacto.setText("ELIMINAR");
        botonEliminarContacto.setFocusable(false);
        botonEliminarContacto.setMinimumSize(new java.awt.Dimension(100, 30));
        botonEliminarContacto.setPreferredSize(new java.awt.Dimension(100, 30));
        botonEliminarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarContactoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(348, 348, 348)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonAgregarContacto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEditarContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscarContacto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEliminarContacto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(etiquetaMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(317, 317, 317))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(275, Short.MAX_VALUE)
                .addComponent(etiquetaTitulo1)
                .addGap(267, 267, 267))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(etiquetaTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaMenu2)
                .addGap(12, 12, 12)
                .addComponent(botonAgregarContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(botonEditarContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonBuscarContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonEliminarContacto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarContactoActionPerformed
    // Validación para usar la misma instancia
    if (ventanaPrincipal.getAgregarContacto() == null) {
        AgregarContacto agregarContacto2 = new AgregarContacto(ventanaPrincipal, ventanaPrincipal.getPanelContenedor2(), modelo);
        ventanaPrincipal.setAgregarContacto(agregarContacto2); 
    }
    ventanaPrincipal.cambiarPanelContenedor2(ventanaPrincipal.getAgregarContacto());
    }//GEN-LAST:event_botonAgregarContactoActionPerformed

    private void botonEditarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarContactoActionPerformed
        editarContacto = new EditarContacto(ventanaPrincipal, ventanaPrincipal.getPanelContenedor2());
        ventanaPrincipal.cambiarPanelContenedor2(editarContacto);
    }//GEN-LAST:event_botonEditarContactoActionPerformed

    private void botonEliminarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarContactoActionPerformed
        EliminarContacto eliminarContacto = new EliminarContacto(ventanaPrincipal, ventanaPrincipal.getPanelContenedor2());
        ventanaPrincipal.cambiarPanelContenedor2(eliminarContacto);
    }//GEN-LAST:event_botonEliminarContactoActionPerformed

    private void botonBuscarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarContactoActionPerformed
        BuscarContacto buscarContacto = new BuscarContacto(ventanaPrincipal, ventanaPrincipal.getPanelContenedor2());
        ventanaPrincipal.cambiarPanelContenedor2(buscarContacto);

    }//GEN-LAST:event_botonBuscarContactoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarContacto;
    private javax.swing.JButton botonBuscarContacto;
    private javax.swing.JButton botonEditarContacto;
    private javax.swing.JButton botonEliminarContacto;
    private javax.swing.JLabel etiquetaMenu2;
    private javax.swing.JLabel etiquetaTitulo1;
    // End of variables declaration//GEN-END:variables
}
